project:
  type: website
  output-dir: docs
website:
  title: "Structures du Monde Actuel"
  navbar:
    left:
      - href: index.qmd
        text: "Index"
      - href: press.qmd
        text: "Presse-Puissance"
      - href: SMA1.qmd
        text: "Puissance"
      - href: press2.qmd
        text: "Presse-Commerce"
      - href: SMA2.qmd
        text: "Commerce"
      - href: press3.qmd
        text: "Presse-Villes"        
      - href: SMA3.qmd
        text: "Villes"
      - href: SMA4.qmd
        text: "Métropoles"
      - href: press4.qmd
        text: "Presse-Métropoles"
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/SMA
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2025, Claude Grasland
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


